import{gestureToAction,cycleMask,inferPointDirection,MASK_IDS}from'./gestures.js';import{loadVision,detect}from'./vision.js';import{drawMask,MASK_LABELS}from'./masks.js';import{createHud,setStatus,flashGesture,setMaskName}from'./hud.js';
const q=s=>document.querySelector(s),intro=q('#intro'),stage=q('#stage'),startBtn=q('#startBtn'),video=q('#camera'),canvas=q('#overlay'),ctx=canvas.getContext('2d'),switchBtn=q('#switchCameraBtn'),soundBtn=q('#soundBtn'),helpBtn=q('#helpBtn'),toggle=q('#gestureToggle'),sheet=q('#gestureSheet'),hud=createHud();let stream,facingMode='user',activeMask='clear',ready=false,soundOn=true,lastKey='',lastAt=0,lastFace=null;const COOL=850;
function resize(){const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0)}
async function camera(){stream?.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:facingMode},width:{ideal:1280},height:{ideal:720}}});video.srcObject=stream;await video.play()}
function beep(){if(!soundOn)return;const A=AudioContext||webkitAudioContext;if(!A)return;const a=new A,o=a.createOscillator(),g=a.createGain();o.frequency.value=520;g.gain.value=.04;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.12);o.onended=()=>a.close()}
function apply(id,msg){activeMask=id;setMaskName(hud,MASK_LABELS[id]);flashGesture(hud,'GESTURE DETECTED',msg);beep()}
function gesture(r,n){if(!r.gestureLabel||r.gestureScore<.62)return;let a=gestureToAction(r.gestureLabel),k=r.gestureLabel;if(r.gestureLabel==='Pointing_Up'){const d=inferPointDirection(r.handLandmarks);if(!d)return;a=d==='right'?'next':'prev';k+=d}if(!a||n-lastAt<COOL)return;lastKey=k;lastAt=n;if(a==='clear')apply('clear','HUMAN MODE');else if(a==='iron')apply('iron','IRON HERO ONLINE');else if(a==='cyber')apply('cyber','CYBER KNIGHT ONLINE');else apply(cycleMask(activeMask==='clear'?MASK_IDS[0]:activeMask,a==='next'?1:-1,MASK_IDS),a==='next'?'NEXT PROFILE':'PREVIOUS PROFILE')}
function render(n){if(ready&&video.readyState>=2){const r=detect(video,n);if(!r.stale){lastFace=r.faceLandmarks||null;gesture(r,n);setStatus(hud,lastFace?'面部锁定 · 抬手做一个手势':'正在寻找你的脸…','ready')}}const r=canvas.getBoundingClientRect();drawMask(ctx,activeMask,lastFace,r.width,r.height,n);requestAnimationFrame(render)}
async function start(){if(!navigator.mediaDevices?.getUserMedia){alert('请使用最新版 Chrome / Safari，并通过 HTTPS 打开。');return}startBtn.disabled=true;startBtn.textContent='正在启动视觉系统…';try{await camera();intro.classList.add('is-hidden');stage.classList.remove('is-hidden');resize();setStatus(hud,'正在加载手势与人脸模型…');await loadVision();ready=true;setStatus(hud,'面部锁定 · 抬手做一个手势','ready')}catch(e){console.error(e);startBtn.disabled=false;startBtn.innerHTML='重新尝试 <span>→</span>';alert('没能启动。请允许相机权限，并检查网络连接。')}}
startBtn.onclick=start;switchBtn.onclick=async()=>{facingMode=facingMode==='user'?'environment':'user';try{await camera();flashGesture(hud,'CAMERA SWITCHED',facingMode==='user'?'FRONT CAMERA':'REAR CAMERA')}catch(e){setStatus(hud,'无法切换摄像头','error')}};soundBtn.onclick=()=>{soundOn=!soundOn;soundBtn.classList.toggle('active',soundOn)};function help(){sheet.classList.toggle('collapsed');const o=!sheet.classList.contains('collapsed');toggle.setAttribute('aria-expanded',String(o));helpBtn.classList.toggle('active',o)}helpBtn.onclick=help;toggle.onclick=help;addEventListener('resize',resize);requestAnimationFrame(render);
